import { UserProfile, StoryItem, Post, Reel, Conversation, HangoutRoom, NotificationItem } from '../types';

export const INITIAL_ACCOUNTS: (UserProfile & { password?: string; emailOrPhone?: string })[] = [
  {
    id: 'user_tafhim',
    username: 'tafhimul_alam',
    fullName: 'Tafhimul Alam',
    emailOrPhone: 'tafhimulalam93@gmail.com',
    password: '123456',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Founder & Tech Creator 📸\nExploring life, visuals, travel & design ✈️\nConnected on Instagram: @tafhim_insta',
    location: 'Dhaka / Dubai',
    website: 'https://tafhimul.com',
    isVerified: true,
    followersCount: 142000,
    followingCount: 389,
    postsCount: 24,
    reelsCount: 12,
    isPrivateAccount: false,
    instagramHandle: 'tafhim_insta',
    isInstagramConnected: true,
    instagramFollowers: '98.4K',
    onlineStatus: 'online',
    lastSeen: 'Active Now',
    joinDate: 'March 2024',
    registeredDevices: [
      {
        id: 'dev_1',
        deviceName: 'iPhone 15 Pro Max',
        platform: 'iOS 17.5 • Safari Mobile',
        location: 'Dhaka, Bangladesh',
        ipAddress: '103.145.23.18',
        lastActive: 'Active Now',
        isCurrent: true,
      },
      {
        id: 'dev_2',
        deviceName: 'MacBook Pro 16"',
        platform: 'macOS Sonoma • Google Chrome',
        location: 'Dubai Marina, UAE',
        ipAddress: '194.67.210.45',
        lastActive: '2 hours ago',
        isCurrent: false,
      },
      {
        id: 'dev_3',
        deviceName: 'iPad Air 5th Gen',
        platform: 'iPadOS 17.4 • Applet',
        location: 'Chittagong, Bangladesh',
        ipAddress: '103.145.23.90',
        lastActive: 'Yesterday at 8:40 PM',
        isCurrent: false,
      },
    ],
    highlights: [
      { id: 'h1', title: 'Travel ✈️', cover: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80' },
      { id: 'h2', title: 'Lifestyle ☕', cover: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&auto=format&fit=crop&q=80' },
      { id: 'h3', title: 'Reels 🎬', cover: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80' },
      { id: 'h4', title: 'Tech 💻', cover: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'user_zara',
    username: 'zara_style',
    fullName: 'Zara Chowdhury',
    emailOrPhone: 'zara@gmail.com',
    password: '123456',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    bio: 'Fashion designer & photography lover 👗✨\nParis | Milan | Dubai',
    location: 'Paris, France',
    website: 'https://zarastyle.fashion',
    isVerified: true,
    followersCount: 380000,
    followingCount: 420,
    postsCount: 112,
    reelsCount: 45,
    isPrivateAccount: false,
    instagramHandle: 'zara_style_official',
    isInstagramConnected: true,
    instagramFollowers: '240K',
    onlineStatus: 'online',
    lastSeen: 'Active Now',
    joinDate: 'January 2024',
    registeredDevices: [
      {
        id: 'dev_z1',
        deviceName: 'iPhone 15 Pro',
        platform: 'iOS 17.5',
        location: 'Paris, France',
        ipAddress: '82.127.15.89',
        lastActive: 'Active Now',
        isCurrent: true,
      },
    ],
    highlights: [
      { id: 'zh1', title: 'Paris 🇫🇷', cover: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&auto=format&fit=crop&q=80' },
      { id: 'zh2', title: 'Looks 👠', cover: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'user_farhan',
    username: 'farhan_dxb',
    fullName: 'Farhan Al-Kareem',
    emailOrPhone: 'farhan@gmail.com',
    password: '123456',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Dubai explorer & automotive filmmaker 🏎️🏙️',
    location: 'Dubai Marina, UAE',
    isVerified: true,
    followersCount: 520000,
    followingCount: 210,
    postsCount: 88,
    reelsCount: 32,
    isPrivateAccount: false,
    instagramHandle: 'farhan_dxb_live',
    isInstagramConnected: true,
    onlineStatus: 'online',
    lastSeen: 'Active Now',
    joinDate: 'February 2024',
    registeredDevices: [
      {
        id: 'dev_f1',
        deviceName: 'Samsung Galaxy S24 Ultra',
        platform: 'Android 14 • Chrome',
        location: 'Dubai Marina, UAE',
        ipAddress: '194.67.211.12',
        lastActive: 'Active Now',
        isCurrent: true,
      },
    ],
  },
];

export const CURRENT_USER: UserProfile = INITIAL_ACCOUNTS[0];
export const AVAILABLE_ACCOUNTS: UserProfile[] = INITIAL_ACCOUNTS;

export const SEED_USERS: UserProfile[] = [
  INITIAL_ACCOUNTS[0],
  INITIAL_ACCOUNTS[1],
  INITIAL_ACCOUNTS[2],
  {
    id: 'user_3',
    username: 'elena_vogue',
    fullName: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=80',
    bio: 'Jewelry artist & visual director 💎 Geneva | Milan',
    location: 'Geneva, Switzerland',
    isVerified: true,
    followersCount: 195000,
    followingCount: 340,
    postsCount: 145,
    reelsCount: 28,
    instagramHandle: 'elena_jewels',
    isInstagramConnected: true,
  },
  {
    id: 'user_4',
    username: 'arian_photo',
    fullName: 'Arian Siddique',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    bio: 'Cinematography & visual storytelling 📸\nDhaka & Tokyo',
    location: 'Dhaka / Tokyo',
    isVerified: true,
    followersCount: 88500,
    followingCount: 412,
    postsCount: 64,
    reelsCount: 19,
    instagramHandle: 'arian_captures',
    isInstagramConnected: true,
  },
  {
    id: 'user_5',
    username: 'sophia_travels',
    fullName: 'Sophia Bennett',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    bio: 'Travel blogger | 45 countries & counting 🌍✈️',
    location: 'London / Bali',
    isVerified: true,
    followersCount: 310000,
    followingCount: 650,
    postsCount: 210,
    reelsCount: 84,
    instagramHandle: 'sophia_wander',
    isInstagramConnected: true,
  },
];

export const INITIAL_STORIES: StoryItem[] = [
  {
    id: 'story_1',
    userId: 'user_tafhim',
    user: {
      username: 'tafhimul_alam',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1080&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: '15m ago',
    caption: 'Golden sunset vibes over the city 🌅✨',
  },
  {
    id: 'story_2',
    userId: 'user_zara',
    user: {
      username: 'zara_style',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1080&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: '42m ago',
    caption: 'Morning in Paris ☕🥐',
  },
  {
    id: 'story_3',
    userId: 'user_farhan',
    user: {
      username: 'farhan_dxb',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1080&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: '1h ago',
    caption: 'Late night drive in Dubai Marina 🏎️🔥',
  },
  {
    id: 'story_4',
    userId: 'user_3',
    user: {
      username: 'elena_vogue',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1080&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: '2h ago',
    caption: 'New jewelry collection teaser 💎',
  },
  {
    id: 'story_5',
    userId: 'user_4',
    user: {
      username: 'arian_photo',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1080&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: '3h ago',
    caption: 'Chasing the horizon 🌊📷',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    userId: 'user_tafhim',
    author: {
      username: 'tafhimul_alam',
      fullName: 'Tafhimul Alam',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'tafhim_insta',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1080&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Catching the golden hour in Dubai. Consistency and vision define every milestone. 🌆✨ #Architecture #Dubai #Photography #Lifestyle',
    tags: ['#Dubai', '#Architecture', '#Lifestyle', '#Sunset'],
    location: 'Downtown Dubai',
    audioTrack: 'Original Audio - Tafhimul Alam',
    likesCount: 14280,
    commentsCount: 384,
    sharesCount: 92,
    isLiked: false,
    isSaved: false,
    isInstagramCrossPosted: true,
    createdAt: '2 hours ago',
    comments: [
      {
        id: 'c1',
        userId: 'user_zara',
        username: 'zara_style',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
        isVerified: true,
        text: 'Incredible lighting! The architecture is sublime 🔥',
        timestamp: '1h ago',
        likes: 24,
      },
      {
        id: 'c2',
        userId: 'user_farhan',
        username: 'farhan_dxb',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        isVerified: true,
        text: 'Classic shot bro! Let’s catch up soon 🛥️',
        timestamp: '45m ago',
        likes: 18,
      },
    ],
  },
  {
    id: 'post_2',
    userId: 'user_zara',
    author: {
      username: 'zara_style',
      fullName: 'Zara Chowdhury',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'zara_style_official',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1080&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Autumn aesthetic in Paris. Details that make everyday moments special 🍂☕ #ParisFashion #OOTD #AutumnVibes',
    tags: ['#ParisFashion', '#OOTD', '#Style', '#Fashion'],
    location: 'Paris, France',
    likesCount: 22890,
    commentsCount: 512,
    sharesCount: 145,
    isLiked: true,
    isSaved: true,
    isInstagramCrossPosted: true,
    createdAt: '4 hours ago',
    comments: [
      {
        id: 'c3',
        userId: 'user_tafhim',
        username: 'tafhimul_alam',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        isVerified: true,
        text: 'Elegance personified! 👏✨',
        timestamp: '3h ago',
        likes: 31,
      },
    ],
  },
  {
    id: 'post_3',
    userId: 'user_farhan',
    author: {
      username: 'farhan_dxb',
      fullName: 'Farhan Al-Kareem',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'farhan_dxb_live',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Pure engineering masterpiece on the track today 🏎️💨 #Supercars #Speed #TrackDay #Porsche',
    tags: ['#Supercars', '#Speed', '#Porsche', '#Dubai'],
    location: 'Dubai Autodrome',
    likesCount: 38400,
    commentsCount: 680,
    sharesCount: 310,
    isLiked: false,
    isSaved: false,
    createdAt: '6 hours ago',
  },
  {
    id: 'post_4',
    userId: 'user_3',
    author: {
      username: 'elena_vogue',
      fullName: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'elena_jewels',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Handcrafted perfection. The new emerald sapphire collection is finally here 💎✨ #Jewelry #LuxuryDesign #Art',
    tags: ['#Jewelry', '#Emerald', '#Sapphire', '#Art'],
    location: 'Geneva, Switzerland',
    likesCount: 15400,
    commentsCount: 290,
    sharesCount: 88,
    isLiked: false,
    isSaved: false,
    createdAt: '8 hours ago',
  },
  {
    id: 'post_5',
    userId: 'user_4',
    author: {
      username: 'arian_photo',
      fullName: 'Arian Siddique',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'arian_captures',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Peaceful turquoise waters. Nature is the greatest artist 🌊🌴 #TravelPhotography #Tropical #Sea #Nature',
    tags: ['#TravelPhotography', '#Tropical', '#Sea', '#Nature'],
    location: 'Maldives',
    likesCount: 19800,
    commentsCount: 320,
    sharesCount: 110,
    isLiked: false,
    isSaved: false,
    createdAt: '12 hours ago',
  },
  {
    id: 'post_6',
    userId: 'user_5',
    author: {
      username: 'sophia_travels',
      fullName: 'Sophia Bennett',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'sophia_wander',
    },
    mediaType: 'image',
    mediaUrls: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1080&auto=format&fit=crop&q=80',
    ],
    caption: 'Desert sunset safari in Dubai 🐪🏜️ Magic in the dunes. #DesertSafari #Dubai #Wanderlust',
    tags: ['#DesertSafari', '#Dubai', '#Wanderlust'],
    location: 'Dubai Desert Conservation Reserve',
    likesCount: 24100,
    commentsCount: 410,
    sharesCount: 175,
    isLiked: true,
    isSaved: false,
    createdAt: '1 day ago',
  },
];

export const INITIAL_REELS: Reel[] = [
  {
    id: 'reel_1',
    userId: 'user_tafhim',
    author: {
      username: 'tafhimul_alam',
      fullName: 'Tafhimul Alam',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'tafhim_insta',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-flying-over-a-modern-city-at-night-42861-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=80',
    caption: 'City of lights from above 🌌 The energy is unmatched! #NightCity #Dubai #Reels #Aesthetic',
    tags: ['#NightCity', '#Dubai', '#Reels', '#Aesthetic'],
    audioTitle: 'Nightfall Beats (VIP Mix)',
    audioArtist: 'Tafhimul Alam',
    likesCount: 54200,
    commentsCount: 1420,
    sharesCount: 890,
    isLiked: false,
    isSaved: false,
    createdAt: '1 day ago',
    viewsCount: 340000,
    isInstagramSync: true,
  },
  {
    id: 'reel_2',
    userId: 'user_farhan',
    author: {
      username: 'farhan_dxb',
      fullName: 'Farhan Al-Kareem',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'farhan_dxb_live',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-sports-car-driving-fast-on-a-curved-road-42636-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
    caption: 'That twin-turbo symphony 🔥🔊 Turn your volume up! #Supercars #Speed #ExoticCars',
    tags: ['#Supercars', '#Speed', '#ExoticCars'],
    audioTitle: 'V10 Engine Symphony',
    audioArtist: 'Farhan DXB',
    likesCount: 89000,
    commentsCount: 2310,
    sharesCount: 1450,
    isLiked: true,
    isSaved: true,
    createdAt: '2 days ago',
    viewsCount: 620000,
    isInstagramSync: true,
  },
  {
    id: 'reel_3',
    userId: 'user_zara',
    author: {
      username: 'zara_style',
      fullName: 'Zara Chowdhury',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
      instagramHandle: 'zara_style_official',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-model-walking-on-a-runway-41275-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    caption: 'Fashion week backstage & runway moments ✨🇫🇷 #ParisFashionWeek #Couture #Style',
    tags: ['#ParisFashionWeek', '#Couture', '#Style'],
    audioTitle: 'Runway Chic - Zara Mix',
    audioArtist: 'Zara Couture',
    likesCount: 67800,
    commentsCount: 1840,
    sharesCount: 980,
    isLiked: false,
    isSaved: false,
    createdAt: '3 days ago',
    viewsCount: 490000,
    isInstagramSync: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    type: 'like',
    fromUser: {
      id: 'user_zara',
      username: 'zara_style',
      fullName: 'Zara Chowdhury',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    text: 'liked your photo.',
    timestamp: '5m ago',
    postThumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&auto=format&fit=crop&q=80',
    isRead: false,
  },
  {
    id: 'notif_2',
    type: 'comment',
    fromUser: {
      id: 'user_farhan',
      username: 'farhan_dxb',
      fullName: 'Farhan Al-Kareem',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    text: 'commented: "Classic shot bro! Let’s catch up soon 🛥️"',
    timestamp: '45m ago',
    postThumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&auto=format&fit=crop&q=80',
    isRead: false,
  },
  {
    id: 'notif_3',
    type: 'follow',
    fromUser: {
      id: 'user_3',
      username: 'elena_vogue',
      fullName: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    text: 'started following you.',
    timestamp: '2h ago',
    isRead: true,
  },
  {
    id: 'notif_4',
    type: 'mention',
    fromUser: {
      id: 'user_4',
      username: 'arian_photo',
      fullName: 'Arian Siddique',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    text: 'mentioned you in a reel caption.',
    timestamp: '1d ago',
    postThumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80',
    isRead: true,
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    isGroup: false,
    participants: [
      CURRENT_USER,
      INITIAL_ACCOUNTS[1], // Zara
    ],
    unreadCount: 1,
    updatedAt: '10m ago',
    lastMessage: {
      id: 'msg_10',
      senderId: 'user_zara',
      recipientId: 'user_tafhim',
      text: 'Hey! Loved your latest post from Downtown Dubai! ✨',
      timestamp: '10m ago',
      status: 'read',
    },
  },
  {
    id: 'conv_2',
    isGroup: false,
    participants: [
      CURRENT_USER,
      INITIAL_ACCOUNTS[2], // Farhan
    ],
    unreadCount: 0,
    updatedAt: '1h ago',
    lastMessage: {
      id: 'msg_20',
      senderId: 'user_farhan',
      recipientId: 'user_tafhim',
      text: 'Are you free for the yacht meetup this Friday? 🛥️',
      timestamp: '1h ago',
      status: 'read',
    },
  },
];

export const INITIAL_MESSAGES_MAP: { [convId: string]: import('../types').ChatMessage[] } = {
  conv_1: [
    {
      id: 'msg_1',
      senderId: 'user_tafhim',
      recipientId: 'user_zara',
      text: 'Hey Zara! How was Paris Fashion Week?',
      timestamp: '11:00 AM',
      status: 'read',
    },
    {
      id: 'msg_2',
      senderId: 'user_zara',
      recipientId: 'user_tafhim',
      text: 'It was breathtaking! Working on a new collection right now 👗',
      timestamp: '11:05 AM',
      status: 'read',
    },
    {
      id: 'msg_10',
      senderId: 'user_zara',
      recipientId: 'user_tafhim',
      text: 'Hey! Loved your latest post from Downtown Dubai! ✨',
      timestamp: '10m ago',
      status: 'delivered',
    },
  ],
  conv_2: [
    {
      id: 'msg_20',
      senderId: 'user_farhan',
      recipientId: 'user_tafhim',
      text: 'Are you free for the yacht meetup this Friday? 🛥️',
      timestamp: '1h ago',
      status: 'read',
    },
  ],
};

export const INITIAL_HANGOUT_ROOMS: HangoutRoom[] = [
  {
    id: 'room_1',
    title: 'Creators & Filmmakers Lounge 🎬',
    topic: 'Cinematic Reel Creation & Lighting Tips',
    host: CURRENT_USER,
    participantsCount: 38,
    activeSpeakers: [CURRENT_USER, INITIAL_ACCOUNTS[1], INITIAL_ACCOUNTS[2]],
    listeners: [SEED_USERS[3], SEED_USERS[4]],
    isLive: true,
    roomType: 'adda_chill',
  },
];

export const CHAT_THEMES = [
  {
    id: 'royal',
    name: 'Royal Classic Blue',
    nameBn: 'রয়্যাল ক্লাসিক ব্লু',
    previewGradient: 'from-blue-600 to-sky-400',
    bubbleMe: 'bg-gradient-to-tr from-blue-600 via-blue-500 to-sky-500 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-slate-700/60',
    borderTint: 'border-blue-500/30',
    bgTint: 'from-blue-950/20 via-[#060913] to-slate-950',
  },
  {
    id: 'sunset',
    name: 'Instagram Sunset',
    nameBn: 'ইন্সটাগ্রাম সানসেট',
    previewGradient: 'from-amber-500 via-rose-500 to-purple-600',
    bubbleMe: 'bg-gradient-to-tr from-amber-500 via-rose-500 to-purple-600 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-rose-500/30',
    borderTint: 'border-rose-500/40',
    bgTint: 'from-rose-950/25 via-[#0c0817] to-slate-950',
  },
  {
    id: 'neon',
    name: 'Cyberpunk Neon',
    nameBn: 'সাইবার নিয়ন',
    previewGradient: 'from-cyan-400 via-blue-500 to-fuchsia-500',
    bubbleMe: 'bg-gradient-to-tr from-cyan-500 via-blue-600 to-fuchsia-500 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-cyan-500/30',
    borderTint: 'border-cyan-500/40',
    bgTint: 'from-cyan-950/25 via-[#060e1a] to-slate-950',
  },
  {
    id: 'emerald',
    name: 'Emerald Jade',
    nameBn: 'এমেরাল্ড গ্রিন',
    previewGradient: 'from-emerald-500 to-teal-400',
    bubbleMe: 'bg-gradient-to-tr from-emerald-600 via-teal-500 to-sky-500 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-emerald-500/30',
    borderTint: 'border-emerald-500/40',
    bgTint: 'from-emerald-950/25 via-[#06120e] to-slate-950',
  },
  {
    id: 'midnight',
    name: 'Midnight Velvet',
    nameBn: 'মিডনাইট ভেলভেট',
    previewGradient: 'from-purple-900 via-indigo-700 to-slate-900',
    bubbleMe: 'bg-gradient-to-tr from-purple-700 via-indigo-600 to-slate-900 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-purple-500/30',
    borderTint: 'border-purple-500/40',
    bgTint: 'from-purple-950/25 via-[#0e0717] to-slate-950',
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom',
    nameBn: 'চেরি ব্লসম',
    previewGradient: 'from-pink-500 via-rose-500 to-purple-500',
    bubbleMe: 'bg-gradient-to-tr from-pink-500 via-rose-500 to-purple-500 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-pink-500/30',
    borderTint: 'border-pink-500/40',
    bgTint: 'from-pink-950/25 via-[#140612] to-slate-950',
  },
  {
    id: 'flame',
    name: 'Crimson Flame',
    nameBn: 'ক্রিমসন গোল্ড',
    previewGradient: 'from-red-600 via-rose-600 to-amber-500',
    bubbleMe: 'bg-gradient-to-tr from-red-600 via-rose-600 to-amber-500 text-white',
    bubblePartner: 'bg-slate-800/90 text-white border border-amber-500/30',
    borderTint: 'border-amber-500/40',
    bgTint: 'from-amber-950/20 via-[#140807] to-slate-950',
  },
];

